spring.application.name=StudentManagement-Dev

# SURGICAL FIX: We use ${SPRING_DATASOURCE_URL} so Jenkins can 
# tell Team 1 to use 'student-m-team1-db' and Team 2 to use 'student-m-team2-db'
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
